-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 02:30:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveidor` (
  `nif_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` INT UNSIGNED NOT NULL,
  `fax` INT NOT NULL,
  PRIMARY KEY (`nif_id`),
  UNIQUE INDEX `proveidors_id_UNIQUE` (`nif_id` ASC) VISIBLE,
  UNIQUE INDEX `proveidors_col_UNIQUE` (`nom` ASC) VISIBLE,
  UNIQUE INDEX `telefon_col_UNIQUE` (`telefon` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `nom` VARCHAR(45) NOT NULL,
  `marca_id` INT NOT NULL,
  `proveidor_nif_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`marca_id`, `proveidor_nif_id`),
  INDEX `fk_marca_proveidor1_idx` (`proveidor_nif_id` ASC) VISIBLE,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  UNIQUE INDEX `proveidor_nif_id_UNIQUE` (`proveidor_nif_id` ASC) VISIBLE,
  UNIQUE INDEX `marca_id_UNIQUE` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_marca_proveidor1`
    FOREIGN KEY (`proveidor_nif_id`)
    REFERENCES `mydb`.`proveidor` (`nif_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `ulleres_id` INT NOT NULL AUTO_INCREMENT,
  `montura` VARCHAR(45) NOT NULL,
  `vidre1` VARCHAR(45) NOT NULL,
  `vidre2` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidre1` VARCHAR(45) NOT NULL,
  `color_vidre2` VARCHAR(45) NOT NULL,
  `preu` DOUBLE NOT NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`ulleres_id`, `marca_id`),
  UNIQUE INDEX `ulleres_id_UNIQUE` (`ulleres_id` ASC) VISIBLE,
  INDEX `fk_ulleres_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_ulleres_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `mydb`.`marca` (`marca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `correu` VARCHAR(45) NOT NULL,
  `client_desde` DATETIME NOT NULL,
  `codi_postal` INT NOT NULL,
  `referencia` INT NULL COMMENT 'id del client que ha recomenat l\'establiment.',
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adreça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adreça` (
  `adreça_id` INT NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `pis` INT NOT NULL,
  `porta` CHAR NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codi_postal` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `nif_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nif_id`),
  INDEX `fk_adreça_proveidor_idx` (`nif_id` ASC) VISIBLE,
  CONSTRAINT `fk_adreça_proveidor`
    FOREIGN KEY (`nif_id`)
    REFERENCES `mydb`.`proveidor` (`nif_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleat` (
  `empleat_id` INT NOT NULL,
  PRIMARY KEY (`empleat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `venda_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `empleat_id` INT NOT NULL,
  `ulleres_id` INT NOT NULL,
  PRIMARY KEY (`venda_id`, `client_id`, `empleat_id`, `ulleres_id`),
  INDEX `fk_venda_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_venda_empleat1_idx` (`empleat_id` ASC) VISIBLE,
  INDEX `fk_venda_ulleres1_idx` (`ulleres_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venda_empleat1`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `mydb`.`empleat` (`empleat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venda_ulleres1`
    FOREIGN KEY (`ulleres_id`)
    REFERENCES `mydb`.`ulleres` (`ulleres_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
