-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 03:39:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincia` (
  `provincia_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`provincia_id`),
  UNIQUE INDEX `provincia_id_UNIQUE` (`provincia_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localitat` (
  `localitat_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `provincia_provincia_id` INT NOT NULL,
  PRIMARY KEY (`localitat_id`, `provincia_provincia_id`),
  INDEX `fk_localitat_provincia_idx` (`provincia_provincia_id` ASC) VISIBLE,
  UNIQUE INDEX `localitat_id_UNIQUE` (`localitat_id` ASC) VISIBLE,
  CONSTRAINT `fk_localitat_provincia`
    FOREIGN KEY (`provincia_provincia_id`)
    REFERENCES `mydb`.`provincia` (`provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `codi_postal` INT NOT NULL,
  `telefon` INT NOT NULL,
  `localitat_id` INT NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `localitat_id`, `provincia_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE,
  INDEX `fk_client_localitat1_idx` (`localitat_id` ASC, `provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_localitat1`
    FOREIGN KEY (`localitat_id` , `provincia_id`)
    REFERENCES `mydb`.`localitat` (`localitat_id` , `provincia_provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`botiga` (
  `botiga_id` INT NOT NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `codi_postal` INT NOT NULL,
  `localitat_id` INT NOT NULL,
  PRIMARY KEY (`botiga_id`, `localitat_id`),
  INDEX `fk_botiga_localitat1_idx` (`localitat_id` ASC) VISIBLE,
  UNIQUE INDEX `botiga_id_UNIQUE` (`botiga_id` ASC) VISIBLE,
  CONSTRAINT `fk_botiga_localitat1`
    FOREIGN KEY (`localitat_id`)
    REFERENCES `mydb`.`localitat` (`localitat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleat` (
  `empleat_id` INT NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cogmons` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `treball` BINARY NOT NULL COMMENT 'Cuiner o repartidor.',
  `botiga_botiga_id` INT NOT NULL,
  PRIMARY KEY (`empleat_id`, `botiga_botiga_id`),
  INDEX `fk_empleat_botiga1_idx` (`botiga_botiga_id` ASC) VISIBLE,
  UNIQUE INDEX `nif_id_UNIQUE` (`empleat_id` ASC) VISIBLE,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_botiga1`
    FOREIGN KEY (`botiga_botiga_id`)
    REFERENCES `mydb`.`botiga` (`botiga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda` (
  `comanda_id` INT NOT NULL,
  `data_comanda` DATETIME NOT NULL,
  `domicili` BINARY NOT NULL COMMENT 'Entrega a domicili, sí o no.',
  `pizzes` INT NOT NULL,
  `hamburgueses` INT NOT NULL,
  `begudes` INT NOT NULL,
  `preu` DOUBLE NOT NULL,
  `client_id` INT NOT NULL,
  `botiga_id` INT NOT NULL,
  `empleat_id` INT NOT NULL,
  `data_entrega` DATETIME NOT NULL,
  PRIMARY KEY (`comanda_id`, `client_id`, `botiga_id`, `empleat_id`),
  INDEX `fk_comanda_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_comanda_botiga1_idx` (`botiga_id` ASC) VISIBLE,
  UNIQUE INDEX `comanda_id_UNIQUE` (`comanda_id` ASC) VISIBLE,
  INDEX `fk_comanda_empleat1_idx` (`empleat_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_botiga1`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `mydb`.`botiga` (`botiga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_empleat1`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `mydb`.`empleat` (`empleat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producte` (
  `producte_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(45) NOT NULL,
  `producte` VARCHAR(45) NOT NULL,
  `imatge` BLOB NOT NULL,
  `preu` INT NOT NULL,
  PRIMARY KEY (`producte_id`),
  UNIQUE INDEX `producte_id_UNIQUE` (`producte_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `categoria_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoria_id`),
  UNIQUE INDEX `categoria_id_UNIQUE` (`categoria_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `producte_producte_id` INT NOT NULL,
  `categoria_categoria_id` INT NOT NULL,
  PRIMARY KEY (`producte_producte_id`, `categoria_categoria_id`),
  INDEX `fk_pizza_categoria1_idx` (`categoria_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_producte1`
    FOREIGN KEY (`producte_producte_id`)
    REFERENCES `mydb`.`producte` (`producte_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pizza_categoria1`
    FOREIGN KEY (`categoria_categoria_id`)
    REFERENCES `mydb`.`categoria` (`categoria_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
