-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 01:02:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuari` (
  `usuari_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `data_naixement` VARCHAR(45) NOT NULL,
  `sexe` BINARY NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codipostal` INT NOT NULL,
  UNIQUE INDEX `usuari_id_UNIQUE` (`usuari_id` ASC) VISIBLE,
  PRIMARY KEY (`usuari_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`premium` (
  `data_inici` DATE NOT NULL,
  `data_renovacio` DATE NOT NULL,
  `pagament` BINARY NOT NULL COMMENT 'tarja o paypal',
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`usuari_id`),
  CONSTRAINT `fk_premium_usuari`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarja` (
  `tarja_id` INT NOT NULL,
  `mes` INT NOT NULL,
  `any` INT NOT NULL,
  `codi_seguretat` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`usuari_id`),
  CONSTRAINT `fk_tarja_premium1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`premium` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paypal` (
  `nom` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`usuari_id`),
  CONSTRAINT `fk_paypal_premium1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`premium` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagament` (
  `numero_ordre` INT NOT NULL,
  `data` DATE NOT NULL,
  `total` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`numero_ordre`, `usuari_id`),
  UNIQUE INDEX `pagament_id_UNIQUE` (`numero_ordre` ASC) VISIBLE,
  INDEX `fk_pagament_premium1_idx` (`usuari_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagament_premium1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`premium` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `playlist_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `numero_songs` INT NOT NULL,
  `data` DATE NOT NULL,
  UNIQUE INDEX `playlist_id_UNIQUE` (`playlist_id` ASC) VISIBLE,
  PRIMARY KEY (`playlist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`esborrat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`esborrat` (
  `data` DATE NOT NULL,
  `playlist_playlist_id` INT NOT NULL,
  PRIMARY KEY (`playlist_playlist_id`),
  CONSTRAINT `fk_esborrat_playlist1`
    FOREIGN KEY (`playlist_playlist_id`)
    REFERENCES `mydb`.`playlist` (`playlist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artista` (
  `artista_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `foto` BLOB NOT NULL,
  PRIMARY KEY (`artista_id`),
  UNIQUE INDEX `artista_id_UNIQUE` (`artista_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `album_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `any` INT NOT NULL,
  `portada` BLOB NOT NULL,
  `artista_id` INT NOT NULL,
  PRIMARY KEY (`album_id`, `artista_id`),
  INDEX `fk_album_artista1_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `mydb`.`artista` (`artista_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`song` (
  `song_id` INT NOT NULL,
  `album_id` INT NOT NULL,
  `titol` VARCHAR(45) NOT NULL,
  `durada` TIME NOT NULL,
  `song` VARCHAR(45) NOT NULL,
  `reproduccions` BIGINT NOT NULL,
  PRIMARY KEY (`song_id`, `album_id`),
  UNIQUE INDEX `song_id_UNIQUE` (`song_id` ASC) VISIBLE,
  INDEX `fk_song_album1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `mydb`.`album` (`album_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`song_has_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`song_has_playlist` (
  `song_id` INT NOT NULL,
  `playlist_id` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`song_id`, `playlist_id`, `usuari_id`),
  INDEX `fk_song_has_playlist_playlist1_idx` (`playlist_id` ASC) VISIBLE,
  INDEX `fk_song_has_playlist_song1_idx` (`song_id` ASC) VISIBLE,
  INDEX `fk_song_has_playlist_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_has_playlist_song1`
    FOREIGN KEY (`song_id`)
    REFERENCES `mydb`.`song` (`song_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_song_has_playlist_playlist1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `mydb`.`playlist` (`playlist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_song_has_playlist_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`segueix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`segueix` (
  `artista_id` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`artista_id`, `usuari_id`),
  INDEX `fk_artista_has_usuari_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  INDEX `fk_artista_has_usuari_artista1_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fk_artista_has_usuari_artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `mydb`.`artista` (`artista_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artista_has_usuari_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colaboracio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`colaboracio` (
  `artista_id` INT NOT NULL,
  `artista_id` INT NOT NULL,
  PRIMARY KEY (`artista_id`, `artista_id`),
  INDEX `fk_artista_has_artista_artista2_idx` (`artista_id` ASC) VISIBLE,
  INDEX `fk_artista_has_artista_artista1_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fk_artista_has_artista_artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `mydb`.`artista` (`artista_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artista_has_artista_artista2`
    FOREIGN KEY (`artista_id`)
    REFERENCES `mydb`.`artista` (`artista_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album_favorit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album_favorit` (
  `album_id` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`album_id`, `usuari_id`),
  INDEX `fk_album_has_usuari_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  INDEX `fk_album_has_usuari_album1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_has_usuari_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `mydb`.`album` (`album_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_album_has_usuari_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`song_favorita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`song_favorita` (
  `song_id` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`song_id`, `usuari_id`),
  INDEX `fk_song_has_usuari_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  INDEX `fk_song_has_usuari_song1_idx` (`song_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_has_usuari_song1`
    FOREIGN KEY (`song_id`)
    REFERENCES `mydb`.`song` (`song_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_song_has_usuari_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
