-- MySQL Script generated by MySQL Workbench
-- Thu Apr 21 01:24:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuari` (
  `usuari_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexe` BINARY NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL COMMENT 'codi postal',
  `password` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `data_naix` DATE NOT NULL,
  PRIMARY KEY (`usuari_id`),
  UNIQUE INDEX `usuari_id_UNIQUE` (`usuari_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `video_id` INT NOT NULL,
  `titol` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(90) NOT NULL,
  `mida` DOUBLE NOT NULL,
  `nom_arxiu` VARCHAR(45) NOT NULL,
  `durada` TIME NOT NULL,
  `thumbnail` BLOB NOT NULL,
  `reproduccions` BIGINT NOT NULL,
  `likes` BIGINT NOT NULL,
  `dislikes` BIGINT NOT NULL,
  PRIMARY KEY (`video_id`),
  UNIQUE INDEX `video_id_UNIQUE` (`video_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etiqueta` (
  `etiqueta_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`etiqueta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canal` (
  `canal_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(90) NOT NULL,
  `data` DATETIME NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`canal_id`, `usuari_id`),
  UNIQUE INDEX `canal_id_UNIQUE` (`canal_id` ASC) VISIBLE,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE,
  INDEX `fk_canal_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  CONSTRAINT `fk_canal_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacio` (
  `usuari_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  `estat` VARCHAR(10) NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `canal_id` INT NOT NULL,
  PRIMARY KEY (`usuari_id`, `video_id`, `canal_id`),
  INDEX `fk_table1_video1_idx` (`video_id` ASC) VISIBLE,
  INDEX `fk_publicacio_canal1_idx` (`canal_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publicacio_canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `mydb`.`canal` (`canal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video_etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video_etiqueta` (
  `video_id` INT NOT NULL,
  `etiqueta_id` INT NOT NULL,
  PRIMARY KEY (`video_id`, `etiqueta_id`),
  INDEX `fk_video_has_etiqueta_etiqueta1_idx` (`etiqueta_id` ASC) VISIBLE,
  INDEX `fk_video_has_etiqueta_video1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_has_etiqueta_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_video_has_etiqueta_etiqueta1`
    FOREIGN KEY (`etiqueta_id`)
    REFERENCES `mydb`.`etiqueta` (`etiqueta_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscripcio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscripcio` (
  `usuari_id` INT NOT NULL,
  `canal_id` INT NOT NULL,
  PRIMARY KEY (`usuari_id`, `canal_id`),
  INDEX `fk_usuari_has_canal_canal1_idx` (`canal_id` ASC) VISIBLE,
  INDEX `fk_usuari_has_canal_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  UNIQUE INDEX `usuari_usuari_id_UNIQUE` (`usuari_id` ASC) VISIBLE,
  UNIQUE INDEX `canal_canal_id_UNIQUE` (`canal_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_has_canal_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuari_has_canal_canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `mydb`.`canal` (`canal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `usuari_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  `sentit` BINARY NULL COMMENT 'like or dislike',
  `data` DATETIME NULL,
  PRIMARY KEY (`usuari_id`, `video_id`),
  INDEX `fk_usuari_has_video_video1_idx` (`video_id` ASC) VISIBLE,
  INDEX `fk_usuari_has_video_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_has_video_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuari_has_video_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `playlist_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`playlist_id`),
  UNIQUE INDEX `playlist_id_UNIQUE` (`playlist_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist_video` (
  `playlist_playlist_id` INT NOT NULL,
  `video_video_id` INT NOT NULL,
  PRIMARY KEY (`playlist_playlist_id`, `video_video_id`),
  INDEX `fk_playlist_has_video_video1_idx` (`video_video_id` ASC) VISIBLE,
  INDEX `fk_playlist_has_video_playlist1_idx` (`playlist_playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_has_video_playlist1`
    FOREIGN KEY (`playlist_playlist_id`)
    REFERENCES `mydb`.`playlist` (`playlist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_playlist_has_video_video1`
    FOREIGN KEY (`video_video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentari` (
  `comentari_id` INT NOT NULL,
  `comentari` VARCHAR(145) NOT NULL,
  `data` DATETIME NOT NULL,
  `usuari_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`comentari_id`, `usuari_id`, `video_id`),
  UNIQUE INDEX `comentari_id_UNIQUE` (`comentari_id` ASC) VISIBLE,
  INDEX `fk_comentari_usuari1_idx` (`usuari_id` ASC) VISIBLE,
  INDEX `fk_comentari_video1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentari_usuari1`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuari` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentari_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`video` (`video_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
